---
lang: pt-BR
title: "Análise Exploratória - Parte II"
subtitle: "Gráficos de séries temporais com o pacote tidyplots"
author: "Letícia Paôla de Souza"
date: today
format:
  html:
    embed-resources: true
    toc: true
    number-sections: true
execute:
  echo: false
  warning: false
  message: false
---
```{r}
#| label: setup
#| echo: false

# Opções de exibição numérica
options(digits = 5, scipen = 999)

# Pacotes usados nesta aula
library(here)
library(tidyverse)
library(tidyplots)

#permite que os gráficos do tidyplots usem os espaço disponível
tidyplots_options(width = NA, height = NA)


# Importação dos dados ---------------------------------------------

# define o caminho relativo do arquivo
caminho_dados <- here("dados/limpos/dados_marketing_limpos.rds")

# importa o arquivo no formato rds
dados_marketing <- read_rds(caminho_dados)

# Verifica os dados importados
glimpse(dados_marketing)
```



## Gráfico da Receita Semanal de Vendas

```{r}

dados_marketing |>
  tidyplot(x = data, y = receita_vendas) |>
  add_line()
```


## Gráfico do Gasto Semanal em Redes Sociais

```{r}

dados_marketing |>
  tidyplot(x = data, y = gasto_redes_sociais) |>
  add_line()
```


## Gráfico do Gasto Semanal em TV

```{r}

dados_marketing |>
  tidyplot(x = data, y = gasto_tv) |>
  add_line()
```


## Gráfico para publicação com tidyplots
```{r}
# define os dados e as variáveis usadas no gráfico
dados_marketing |>
  tidyplot(x = data, y = receita_vendas) |>
  # desenha a linha da série temporal
  add_line(linewidth = 0.8, color = "steelblue") |>
  # nomeia os eixos com textos claros e unidade de medida
  adjust_x_axis_title("Semana") |>
  adjust_y_axis_title("Receita semanal de vendas (em US$ mil)") |>
  # informa a fonte dos dados
  add_caption("Fonte: dados simulados pelo professor.") |>
  # aumenta o tamanho da fonte para melhorar a leitura
  adjust_font(fontsize = 12)
```

